# Generated by Django 6.0.3 on 2026-03-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appraisal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="appraisal.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="journal",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "performance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisals",
                        to="appraisal.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="appraisal.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "funding_agency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="appraisal.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="appraisal.faculty",
                    ),
                ),
            ],
        ),
    ]
